# Copyright 2022 Wayties, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FacxV2xInd.msg
# This message contains facility v2x information with sub-message of WXS.

WxsHeader    wxs_header # WxsHeader.msg
MacLayer     mac_layer  # MacLayer.msg
Ieee1609dot3 ieee_dot3  # Ieee1609dot3.msg
Ieee1609dot2 ieee_dot2  # Ieee1609dot2.msg
SaeJ2735     sae_j2735  # SaeJ2735.msg
